### PR TITLE
Fix Trello card closing when opening project/tag dropdown

### LINKED ISSUE #1622: TRELLO card gets closed when project dropdown is clicked
Please follow this guide when creating a new issue. This speeds up the process of replicating the issue and finding a solution.

### Environment details

* Operation system: OS Name	Microsoft Windows 10 Enterprise

* Extension version: 1.52.0

### Expected behavior
when I open the toggl button popup on the Trello card and I try to choose a project I expect the the trello card to stay open. 

### Actual behavior
when I open the toggl button popup on the Trello card and I try to choose a project the trello card closes 
### Steps to reproduce the behavior
go to trello 
open a card 
click "start Timer"
click on project dropdown
### Additional details
Happens in chrome and firefox
also on colleague computer
* screenshots or screencapture
image

### PR DESCRIPTION
**Pull request by lise-toggl**
## :star2: What does this PR do?

Fixes Trello card closing when you click on the edit popup's project or tag dropdowns.

## :bug: Recommendations for testing

1. Open a Trello card
2. Click the "Start timer" link
3. On the edit popup, open the project or tag dropdown

The Trello card should no longer close in the background.

## :memo: Links to relevant issues or information

First two commits are from #1625 which should be merged first.

Closes #1622.

### CODE REVIEW

File: src/scripts/content/atlassian.js [hunk 1]
```diff
@@ -54,7 +54,8 @@ togglbutton.render(
     const link = togglbutton.createTimerLink({
       className: 'jira2018',
       description: getDescription(issueNumberElement),
-      projectName: getProject
+      projectName: getProject,
+      container: '#jira-issue-header'
```
Comment (langri-sha) [inline src/scripts/content/atlassian.js]: :mag: :eyes:

**Comment by lise-toggl** [comment]
@langri-sha rebased on master which fixed the conflicts and also removed the two extra commits :hugs:
