### PR TITLE
Fix Jira kanban board buttons

### LINKED ISSUE #1408: Jira Kanban Board Issue
* **OS version**: Windows 10
* **Browser version**: 74.0.3729.131
* **Extension version**: TogglButton/1.35.0-jira2018

#### Relevant integration (if any):

Jira: https://....atlassian.net (their URL is visible in the recording they sent over, it's in the [**intercom](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/22023298488) convo**.

### 🐛 Describe the bug

When they open up a Kanban board card the Toggl Button shows up only for a moment and goes away after the full content of additional info on the right side is loaded, you'll see that on the video they sent over. 

### Expected behaviour

The Toggl Button should not go away. 

### Steps to reproduce

Was not able to reproduce this with our Jira test account, actually, even with the Jira integration enabled I was not able to see the button at all.

### PR DESCRIPTION
**Pull request by tcrammond**
Please remember the [Contributing Guidelines](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md) :heart:

## :star2: What does this PR do?

Fixes #1408. Removes an integration block that's not needed.

## :bug: Recommendations for testing

To repro on master:

1. Ensure `atlassian.net` origin is enabled
2. Go to the [test Jira](https://togglbutton.atlassian.net/secure/RapidBoard.jspa?rapidView=1)
3. Click on a card after everything has loaded
4. See the Toggl button appear briefly and then vanish again

After changes, to ensure that the "sprint modals" still continue to function (I removed a whole block of code):

1. Go to [scrum project sprint view](https://togglbutton.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=TBSP)
2. Click on an item
3. The modal will appear and a Toggl button should be inserted. Once.

All changes should be tested across Chrome and Firefox.

### CODE REVIEW

File: src/scripts/origins.js [hunk 1]
```diff
@@ -22,11 +22,11 @@ export default {
   },
   'atlassian.com': {
     url: '*://*.atlassian.com/*',
-    name: 'Atlassian'
+    name: 'Atlassian / Jira'
```
Comment (shantanuraj) [inline src/scripts/origins.js]: This broke `TogglButton.extractDomain` for me it wanted to resolve the script name as

image

Adding a file key (value being 'atlassian.js') should fix it

File: src/scripts/origins.js [hunk 2]
```diff
@@ -22,11 +22,11 @@ export default {
...
   },
   'atlassian.net': {
     url: '*://*.atlassian.net/*',
-    name: 'Atlassian',
+    name: 'Atlassian / Jira',
```
Comment (shantanuraj) [inline src/scripts/origins.js]: Same as above

**Comment by tcrammond** [comment]
👍 fixed
