### PR TITLE
fix(teamwork): Reposition Toggl Button after UI redesign

### LINKED ISSUE #1716: TeamWork integration is no longer visible
* **Extension version**: 1.60.7

### 🐛 Describe the bug

The Toggl Button icon is no longer appearing on the TeamWork page - the page looks different from what is shown in the original Toggl Button screenshots. 

### Expected behaviour

Toggl Button should show up on TeamWork page as shown in the screenshots.

### PR DESCRIPTION
**Pull request by kornelijepetak**
## :star2: What does this PR do?

There was a UI change in the Teamwork app. 
This PR fixes the integration.

The Toggl Button is visible at:

* Task list
* Single task view in side-view
* Single-page task view

## :bug: Recommendations for testing

Make sure it's visible and working in both browsers: 
image

## :memo: Links to relevant issues or information

Closes #1716

### CODE REVIEW

File: src/scripts/content/teamwork.js [hunk 1]
```diff
@@ -132,8 +132,41 @@ togglbutton.render(
...
     });
 
-    link.style.margin = "3px 0 0 7px";
+    link.style.margin = '3px 0 0 7px';
 
     container.appendChild(link);
   }
 );
+
+// Teamwork (July 2020)
```
Comment (rylek90) [inline src/scripts/content/teamwork.js:141]: Nitpick: usually we put newest integration's version on top
