### PR TITLE
fix(jira): Fix button not showing on dialog view

### LINKED ISSUE #1913: Button not showing in Atlassian/Jira
* **OS version**: macOS
* **Browser version**: 88.0.4324.96
* **Extension version**: TogglButton/1.69.0

#### Relevant integration (if any):
Atlassian/Jira 
### 🐛 Describe the bug

The button is not showing. 
image

### Expected behaviour

The button should show on this view 

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to ...
2. ...

### Other details or context

[Case 1
](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481307024813)
[Case 2](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481307026536)

### PR DESCRIPTION
**Pull request by dpsxp**
## :star2: What does this PR do?
Fix Button not showing up when using the dialog view for Issues on Jira

## :bug: Recommendations for testing
So Jira has multiple ways to view the Issue:
- Single Page
- Dialog view on Kanban Board

#### Go to Jira
- <domain>/secure/ViewPersonalSettings.jspa
- Jira Labs, allow new Issue view mode
- Open one Issue
- Check if the button still showing

#### Kanban
- Go to Kanban board view
- Click on an Issue
- Check if the button will show up in the dialog
- Check if the button still getting all the information (Issue and Project)

#### Regression
- Go to Jira
- With the old view mode, check if the button still working

## :memo: Links to relevant issues or information
close #1913

### CODE REVIEW

File: src/scripts/content/atlassian.js [hunk 1]
```diff
@@ -61,14 +61,18 @@ togglbutton.render(
...
+    try {
+      const link = togglbutton.createTimerLink({
+        className: 'jira2018',
+        description: getDescription(issueNumberElement),
+        projectName: getProject,
+        container: '#jira-issue-header'
+      });
+
+      container.appendChild(link);
+    } catch (e) {
```
Comment (dpsxp) [inline src/scripts/content/atlassian.js:73]: This is intentional, so we can have some information when something goes wrong.

**Review by rylek90 — APPROVED** [review]
LGTM :rocket:
