### PR TITLE
Freshdesk: remove child elements from subject

### LINKED ISSUE #1323: FreshDesk Integration Adding Button Name to TE Description
#### Relevant integration (if any):

TogglButton and FreshDesk (new FreshDesk "Mint" UI)

### 🐛 Describe the bug

When the "Meta" button appears next to the ticket name, the TogglButton occasionally picks up the word "meta" and adds it to the TE description. 

### Expected behaviour

TogglButton shouldn't use button names for TE description. 

### Screenshot 

untitled

[Intercom case from user ](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/19196386078)

### PR DESCRIPTION
**Pull request by tcrammond**
Please remember the [Contributing Guidelines](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md) :heart:

## :star2: What does this PR do?

This prevents any extra controls in the UI being included in the TE description. Fixes #1323.

## :bug: Recommendations for testing

This happens for "Portal" tickets. Example: https://togglbutton.freshdesk.com/a/tickets/10

## :memo: Links to relevant issues or information

 Fixes #1323.

### CODE REVIEW

**Comment by shantanuraj** [comment]
@tcrammond the popup isn't showing up for me on this branch

File: src/scripts/content/freshdesk.js [hunk 1]
```diff
@@ -31,8 +31,13 @@ togglbutton.render('.page-actions__left:not(.toggl)', { observe: true }, elem =>
 
   const descriptionSelector = () => {
     const ticketNumber = $('.breadcrumb__item.active').textContent.trim();
-    const subject = $('.ticket-subject-heading').textContent.trim();
-    return `${ticketNumber} ${subject}`;
+    // Remove other buttons/controls from the ticket subject
+    const subjectElement = $('.ticket-subject-heading').cloneNode(true);
+    for (let i = 0; i < subjectElement.children.length; i++) {
```
Comment (shantanuraj) [inline src/scripts/content/freshdesk.js]: Not something major but I'd prefer a for-of or for-each loop

```suggestion
    for (let child of subjectElement.children) {
        subjectElement.removeChild(child);
```

or 

```suggestion
    [...subjectElement.children].forEach(child => subjectElement.removeChild(child));
```
