### PR TITLE
Fix Google Calendar new UI

### LINKED ISSUE #1234: Button missing from Google Calendar (Chrome)
* **OS version**: macOS Mojave 10.14.1
* **Browser version**: Version 71.0.3578.98
* **Extension version**: Version (1.17.0)

### 🐛 Describe the bug

Google Calendar has updated their design, Toggl Button no longer displayed. 

### Expected behaviour

Toggl Button present in the updated Google Calendar views. 

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to https://calendar.google.com
2. See no button

### Other details or context

User reported issue in [conversations/20031234511](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/20031234511), problem reproduced by myself.

### PR DESCRIPTION
**Pull request by tcrammond**
Please remember the [Contributing Guidelines](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md) :heart:

## :star2: What does this PR do?

Update calendar selectors; hopefully more safe now.

Remove dead code for old version(s) of calendar. I don't think any of that was still functional anywhere.

## :bug: Recommendations for testing

All changes should be tested across Chrome and Firefox.

Button appears and works when you click on an event and see the "popup".

FYI the behaviour can be *slightly* funky - when you submit the toggl edit form, the calendar popup will close. Probably not trivial to work around, not working on that here.

## :memo: Links to relevant issues or information

Closes #1234.

### CODE REVIEW

File: src/scripts/content/google-calendar.js [hunk 1]
```diff
@@ -1,95 +1,25 @@
...
+  if ($('.toggl-button', elem)) {
+    return;
   }
 
-  if (description) {
-    insertButton(elem, description);
-  }
-});
+  // Grab the "toolbar" by finding "Close" button, which is _always_ present.
+  const target = $('[aria-label="Close"]', elem).parentElement.nextSibling;
```
Comment (Phenome) [inline src/scripts/content/google-calendar.js]: I'm getting an error here:
```
Error: TypeError: Cannot read property 'parentElement' of null
    at togglbutton.render.elem (/C:/Users/live/devel/toggl-button/dist/chrome/scripts/content/google-calendar.js:13)
    at Object.renderTo (webpack:///./scripts/common.js?:157)
    at MutationObserver.eval (webpack:///./scripts/common.js?:126)
```
When clicking any event on the calendar
