### PR TITLE
fix(microsoft-todo): Add support for to-do.microsoft.com domain

### LINKED ISSUE #1312: Microsoft Todo integration broken
* **Extension version**: Latest

#### Relevant integration (if any):

Microsoft Todo

### 🐛 Describe the bug

It does not show Toggl Buttons anymore. Something weird is also happening with the search bar which  hopefully isn't because of the integration 🙈

### PR DESCRIPTION
**Pull request by shantanuraj**
Please remember the [Contributing Guidelines](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md) :heart:

## :star2: What does this PR do?

- Restore toggl button support for Microsoft To-Do
- They seem to have changed their domain from todo.microsoft.com to to-do.microsoft.com
- Also insert the button to the left of the star button

image

## :bug: Recommendations for testing

- Enable Microsoft To-Do integration
- Go to to-do.microsoft.com 
- Add some tasks
- Toggl Button should appear in the task rows

All changes should be tested across Chrome and Firefox.

## :memo: Links to relevant issues or information

Closes #1312

> **Note:** After merging the PR update the screenshot at https://github.com/toggl/toggl-button/wiki/Where-can-I-find-the-Button%3F#microsoft-to-do use the one on this PR

### CODE REVIEW

File: src/scripts/content/microsoft-to-do.js [hunk 1]
```diff
@@ -16,12 +16,12 @@ togglbutton.render('.taskItem-body:not(.toggl)', { observe: true }, function (
       : '';
 
   const link = togglbutton.createTimerLink({
-    className: 'microsoft-todo',
+    className: 'ms-todo-list',
```
Comment (tcrammond) [inline src/scripts/content/microsoft-to-do.js]: ⚠️ let's not change this yet, it'll break analytics data consistency *(yeah..)*. Save that disruption for #1292 😁

Comment (shantanuraj) [reply src/scripts/content/microsoft-to-do.js]: Restored :+1:
