### PR TITLE
fix(any.do): Update description and project selectors

### LINKED ISSUE #1551: Any.do: Description not fetched in list view
* **OS version**: Ubuntu 19.10
* **Browser version**: Chrome 78
* **Extension version**: 1.45

#### Relevant integration (if any):

[Any.do](https://desktop.any.do/tasks/)

### 🐛 Describe the bug

In the tasks list, the description is not fetched when starting a timer:
anydo

### Expected behaviour

The description should be fetched

### Steps to reproduce

1. Go to Any.do
2. Add a task
3. Start a timer for that task in the list view

### Other details or context

Found while working on #1550

### LINKED ISSUE #1553: Improve Any.do project selection
### Describe the changes you'd like

Select the correct project when possible in Any.do

### Relevant links or screenshots

When moving from the "All Tasks" page to another project's page, the task list items don't update their project (i.e. still has "All Tasks" set as their project).

### PR DESCRIPTION
**Pull request by lise-toggl**
## :star2: What does this PR do?

Gets the correct task description from Any.do's task list.

## :bug: Recommendations for testing

Track an item from the task list and check the correct description is used.

## :memo: Links to relevant issues or information

Closes #1551 

Also closes #1553

### CODE REVIEW

File: src/scripts/content/anydo.js [hunk 1]
```diff
@@ -28,13 +28,13 @@ togglbutton.render(
   '.TaskListRow[draggable=true]:not(.toggl)',
   { observe: true },
   elem => {
-    const descriptionElem = $('input', elem);
+    const descriptionElem = elem.querySelector('.TaskItem__label__text__title').textContent;
```
Comment (tcrammond) [inline src/scripts/content/anydo.js]: We should change this into a function that returns the description string, like we do in more modern integrations (usually called something like `descriptionSelector` if you need a reference)

This will mean that we'll always grab the latest description, even after the user might have changed it in the `any.do` UI.

Comment (lise-toggl) [reply src/scripts/content/anydo.js]: Thanks! I've updated all of them to work this way :+1:
