### PR TITLE
Move workflowy to minimal button

### LINKED ISSUE #1711: WorkFlowy integration broken
* **OS version**: not important
* **Browser version**: not important
* **Extension version**: Version 1.60.7

#### Relevant integration (if any):

WorkFlowy - workflowy.com

### 🐛 Describe the bug

The Toggl Button no longer appears on WorkFlowy because they had a pretty major rewrite recently

### Expected behaviour

The Toggl Button should appear 

### Other details or context, additional notes:

WorkFlowy is not listed on the [Integrations](https://toggl.com/integrations/) page or the ["Where can I find the Button?"](https://github.com/toggl/toggl-button/wiki/Where-can-I-find-the-Button%3F#wordpress) page

### PR DESCRIPTION
**Pull request by BeksOmega**
Please remember the [Contributing Guidelines](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md) :heart:

## :star2: What does this PR do?

Fixes the workflowy integration by removing the old context menu functionality. It now uses a permanent minimal button attached to the header.

Here is what the integration looks like now:
NewUI
When you click it it starts a timer for the bullet you last interacted with. If you haven't interacted with a bullet yet, it starts the timer for the top bullet on the page. You can also see the timer it will start when you hover over it:
HoverTip

### Top Bullet Test
1. Open workflowy.
2. Click the timer immediately.
3. Observe how it starts a "home" timer. (home is the name of the invisible top bullet)

### Bullet Test 1
1. Open Workflowy.
2. Create some bullets.
3. Click around on them.
4. Observe how the timer starts for the latest bullet you interacted with.

### Bullet Test 2
1. Open workflowy.
2. Create some bullets with sub-bullets.
3. Open and close some of the bullet drop-downs.
4. Observe how the timer starts for the latest bullet you interacted with.

## :memo: Links to relevant issues or information

Closes #1711

### CODE REVIEW

File: src/scripts/content/workflowy.js [hunk 1]
```diff
@@ -1,82 +1,35 @@
...
-
-    const tagsSelector = () => {
-      return getTags($bulletInfo);
-    };
-
-    const link = togglbutton.createTimerLink({
-      className: 'workflowy',
-      description: descriptionSelector,
-      tags: tagsSelector
+    document.addEventListener('focusin', function (e) {
```
Comment (tcrammond) [inline src/scripts/content/workflowy.js:17]: I think we should try to be good citizens here, and ensure there's only one listener added. It's possible the `togglbutton.render` callback will run multiple times over the lifetime of the browser tab and add many listeners.

One option might be to simply move `document.addEventListener..` to the root of the file?

**Comment by BeksOmega** [comment]
Updated and retested! Thanks for the great suggestions :D

File: src/scripts/content/workflowy.js (hunk 1 above)
Comment (BeksOmega) [reply src/scripts/content/workflowy.js]: Done!

**Comment by lprsd** [comment]
Doesn't work again; seems like workflowy has had another update.

This time, when you capture the data from the page, It would be way more useful to capture the entire hierarchy of the specific bullet. (and enable part of it to be used as a project in Toggl.)
