### PR TITLE
Hotfix for origins not begin fetched

### LINKED ISSUE #1360: Toggl Button missing in all integrations
* Windows 10 Pro v10.0.17763: 
* Google Chrome v73.0.3683.86 : 
* Toggl Button v1.24.0 : 

### 🐛 Describe the bug

The Toggl Button does not show up in any integration anymore. I have the following integrations enabled:
* atlassian.com
* atlassian.net
* bitrix24.com
* bitbucket.org
* github.com
* trello.com

I looked up in all of these sites, and the "Start Timer" button is missing (as shown for example in the screenshots from BitBucket and Trello).

### Expected behaviour

I expected the Start/Stop Button to show up in these pages, as shown in the attached screenshots.

### Other details or context

I have already tried removing and reinstalling the extension, clearing the cache and browsing data, and also uninstalling and reinstalling Chrome. None of them made any difference.

Captura 1
Captura 2

### PR DESCRIPTION
**Pull request by shantanuraj**
Closes #1360

Please remember the [Contributing Guidelines](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md) :heart:

## :star2: What does this PR do?

- Pass correct defaults to `get` method
- Use origins from `this.get` instead of global origins directly
- Fix file name calculation in `getOriginFileName` 

## :bug: Recommendations for testing

All changes should be tested across Chrome and Firefox.

- Enable a few integrations
- They should work correctly
- Check custom domain integrations
- Check that `any.do` works, as it uses a subdomain which operates a little differently

## :memo: Links to relevant issues or information

Closes #1360

### CODE REVIEW

File: src/scripts/lib/db.js [hunk 1]
```diff
@@ -205,6 +234,10 @@ export default class Db {
       });
   }
 
+  setLocal (key, value) {
```
Comment (Phenome) [inline src/scripts/lib/db.js]: Since we're doing `setLocal`, maybe we should also do `getLocal` to replace `localstorage.getItem()` calls
