### PR TITLE
Fix bitrix for iframes

### LINKED ISSUE #1883: Bitrix24 integration issue with custom domains
* **OS version**: OS X 10.15.7
* **Browser version**: 86.0.4240.198
* **Extension version**: 1.66.10

#### Relevant integration (if any):

Bitrix24 - bitrix24.com / custom domains

### 🐛 Describe the bug

Track Button works with the bitrix24.com domain. Bitrix24 Russian cloud accounts are based in the .ru zone and a custom domain is needed but it doesn't work with a custom domain. 

### Expected behavior

For the user to add their Bitrix subdomain as a custom domain (for example toggl.bitrix24.com) and get the integration to work that way. 

### Steps to reproduce

Steps to reproduce the behaviour:
1. Log into Bitrix24
2. Try to add your Bitrix24 subdomain as a custom domain in the settings page > integrations view 
3. Refresh the Bitrix web app and see if it worked

For example, I got the following URL from the Bitrix24 web app: https://b24-9iehx3.bitrix24.com/company/personal/user/1/tasks/

The "b24-9iehx3" is the custom/random subdomain that was assigned when I added "https://b24-9iehx3.bitrix24.com" as a custom domain for the Track Button extension the integration did not work.

[Intercom case reference 
](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/106481305548169)

### PR DESCRIPTION
**Pull request by Phenome**
Please remember the [Contributing Guidelines](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md) :heart:

## :star2: What does this PR do?
Our selector doesn't work for elements within iframes.
This PRs adds this functionality, and updates the bitrix content script to make use of it.

Also, there was a missing closing braces on our styles, so I added that.

## :bug: Recommendations for testing
* Sign up for a bitrix account.
* Go to tasks and projects
  image
* Click a task, it should open in an iframe, and have the toggl button
* Refresh the page. The task should open on the main document, and still have the button

All changes should be tested across Chrome and Firefox.

## :memo: Links to relevant issues or information
Closes #1883

### CODE REVIEW

File: src/scripts/common.js [hunk 1]
```diff
@@ -143,16 +145,28 @@ window.togglbutton = {
                     clearTimeout(debouncer);
                   }
                   debouncer = setTimeout(function () {
-                    togglbutton.renderTo(selector, renderer);
+                    if (opts.iframeSelector) {
+                      togglbutton.renderToIframe(opts.iframeSelector, selector, renderer);
+                    } else {
+                      togglbutton.renderTo(selector, renderer);
+                    }
```
Comment (rylek90) [inline src/scripts/common.js:152]: I honestly would do one `togglbutton.render(selector, renderer, context: 'iframe' | 'document', optionaliframeSelector)` but I don't know which approach is better 🙈

File: src/styles/style.css [hunk 2]
```diff
@@ -1559,3 +1559,4 @@ body.notion-body.dark .toggl-button.notion {
   font-weight: bold;
   position: relative;
   top: -3px;
+}
```
Comment (rylek90) [inline src/styles/style.css:1562]: 🙈

**Review by rylek90 — APPROVED** [review]
This PR is constructed with clean code and solid principles in mind. I'm glad that we have so awesome external contributors! LGTM 🚀
