### PR TITLE
Fix google calendar with graphics

### LINKED ISSUE #1242: Toggl Button missing from events with graphics
* **OS version**: macOS Mojave 10.14.1
* **Browser version**: Version 71.0.3578.98
* **Extension version**: Version (1.17.1)

### 🐛 Describe the bug

Toggl Button doesn't appear when calendar events have graphics on them

### Expected behaviour

Toggl Button present in the Calendar event when graphics are included.

### Steps to reproduce

1. Go to https://calendar.google.com
2. Create a calendar event with "eat breakfast" (or any other that would trigger automatic graphic)
3. See no button

### Other details or context

User reported issue in [conversations/20105859581](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/20105859581), I was able to reproduce the issue

### PR DESCRIPTION
**Pull request by ezaki**
Please remember the [Contributing Guidelines](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md) :heart:

## :star2: What does this PR do?

Fix google calendar event button with graphics.

without graphics
default

with graphics
graphics

## :bug: Recommendations for testing

Chrome and Firefox work well.

## :memo: Links to relevant issues or information

Fix #1242

### CODE REVIEW

File: src/scripts/content/google-calendar.js [hunk 1]
```diff
@@ -20,7 +20,8 @@ togglbutton.render('div[data-chips-dialog="true"]', { observe: true }, elem => {
 
   const link = togglbutton.createTimerLink({
     className: 'google-calendar-modern',
-    description: getDescription
+    description: getDescription,
+    buttonType: 'minimal'
```
Comment (tcrammond) [inline src/scripts/content/google-calendar.js]: we shouldn't change the button to minimal. It's unfortunate that some graphic backgrounds will clash with the text, but we want to keep the full button for regular events.

Comment (ezaki) [reply src/scripts/content/google-calendar.js]: OK!
I changed it.

image
