### PR TITLE
Fix salesforce permission and button placement

### LINKED ISSUE #768: Toggl Button Missing in Salesforce
Please follow this guide when creating a new issue. This speeds up the process of replicating the issue and finding a solution.

### Environment details

* Operation system: Mac OSX 10.10.5
* Extension version: 1.1.2

### Expected behavior

Should be a red Toggl button next to Salesforce "My tasks"

### Actual behavior

Button not found anywhere. Looks like Salesforce has updated their cloud environment, possibly that's what broke the integration.

### Additional details

* screenshots or screencapture
screen shot 2017-02-26 at 10 54 36

### PR DESCRIPTION
**Pull request by LulzAugusto**
closes #768

### CODE REVIEW

**Comment by syko** [comment]
Can you address #764 in this PR as well?

It seems that custom domains are in the form `https://<domain>.my.salesforce.com`
image

**Comment by LulzAugusto** [comment]
Sure. I'll take a look 👍

**Comment by LulzAugusto** [comment]
Ready for another review. Now it should work with the old and the new UI, under a subdomain or not.

File: src/scripts/db.js [hunk 1]
```diff
@@ -42,9 +42,9 @@ var Db = {
     }
 
     if (!TogglOrigins[origin]) {
-      // Handle cases where subdomain is used (like web.any.do, we remove web from the beginning)
+      // Handle cases where subdomain is used (like web.any.do (or sub1.sub2.any.do), we remove web from the beginning)
       origin = origin.split(".");
-      origin.shift();
+      while (origin.length > 2) { origin.shift(); }
```
Comment (syko) [inline src/scripts/db.js]: Still not letting you off the hook. I believe this will fail with SLD-enabled domains such as `.co.uk`.
https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains shows there's a hefty number of such TLDs.
The only catch-all solution I can think of is to check `TogglOrigins` at each iteration and hope that we never introduce an origin that is just `com` or `co.uk`.

**Comment by LulzAugusto** [comment]
@syko Crap I forgot about those, but now it should work. (needs rebase)
