### PR TITLE
fix(pomodoro): Improve pomdoro timer sync on new TEs

### LINKED ISSUE #1801: Pomodoro issue when a new timer is started via the API
* **OS version**: Linux x86_64
* **Browser version**: Chrome 83.0.4103.116
* **Extension version**: 1.64.3

### 🐛 Describe the bug

1) I start p. timer A
2) 10 min remaining on A
3) I call timer B from api
4) chrome extension switches to B and starts a new pomodoro timer with full 25 min left
5) after a few seconds B terminates and pretends it has finished 25 min into the future
### Expected behaviour

Starting a new TE should just reset the Pomodoro interval and not stop the new TE after a few seconds adding the Pomodoro interval time to it's end time.

### Other details or context

Step one, the user referees to the initial timer as the "Pomodoro" timer because they most likely have the countdown view enabled so I guess they refer to it as starting a Pomodoro timer

One nuance here is the fact that they are using an app on their phone to start time entries via the API. They basically have a shortcut for a call to start a running timer but they also use the Toggl Button extension to see Pomodoro.

This issue is possibly related to https://github.com/toggl/toggl-button/issues/1768 and/or https://github.com/toggl/toggl-button/issues/1768#issuecomment-663013721

Intercom thread /106481300034756

### PR DESCRIPTION
**Pull request by dpsxp**
## :star2: What does this PR do?
Improve Pomodoro timer sync when creating TEs on other apps/API. The Pomodoro timer should restart when getting new TEs from other services/API

## :bug: Recommendations for testing
- Turn on Pomodoro 
- I would suggest setting a small interval so you can see the animation better
- Start a new using the extension
- After a few minutes (before the Pomodoro ends) make an API call to start a new running TE.
- The extension should change the running TE to newly created one and set the Pomodoro state based on the current duration of the new TE. 
- If the new TE has a duration already bigger than the Pomodoro interval than the animation should go back to 0% and no alarm should trigger 

#### Sanity check
- Check if Pomodoro still working as expected when only using the extension 
- Updating the duration of TEs should also remove the timer if the new duration is bigger than the interval settings

## :memo: Links to relevant issues or information

close #1801 related #1768

### CODE REVIEW

**Comment by kornelijepetak** [comment]
@dpsxp sorry for taking this long.

I've noticed one thing:
When I run another TE, the TB popup changes to the newly running TE, however, not in the Pomodoro focus mode. It shows as a regular TE (no circle, just timer log).

Is that intentional?

**Review by rylek90 — CHANGES_REQUESTED** [review]
Can we please rebase it to work with post-rebrand changes? :pray: 

Mostly looks good, I wasn't able to enable focus mode on this branch, though :cry:

**Comment by dpsxp** [comment]
Focus mode should be back now 👍

**Review by rylek90 — APPROVED** [review]
LGTM 🚀

File: src/scripts/background.js [hunk 1]
```diff
@@ -688,43 +689,58 @@ window.TogglButton = {
...
-    TogglButton.pomodoroFocusMode = await db.get('pomodoroFocusMode');
-    const interval = parseInt(TogglButton.pomodoroInterval, 10) * 60000;
-    if (duration < interval) {
-      TogglButton.triggerPomodoroAlarm(interval - duration);
-    }
+    TogglButton.triggerPomodoroAlarm(duration);
   },
 
-  triggerPomodoroAlarm: async function (value) {
+  triggerPomodoroAlarm: async function (duration) {
```
Comment (kornelijepetak) [inline src/scripts/background.js:697]: Kudos for naming things.

**Review by kornelijepetak — APPROVED** [review]
Tried. Works. Shipit.
