### PR TITLE
fix(asana): Update project selector for My Tasks page

### LINKED ISSUE #1757: TB is not matching projects when used in Asana [My Tasks view]
* **OS version**: Windows 10
* **Browser version**: 83.0.4103.106
* **Extension version**: 1.62.1.

#### Relevant integration (if any):

Asana [My Tasks view]

### 🐛 Describe the bug

When using TB in Asana on My Tasks view, the project is not being picked up even though matching project exists in Toggl. However, the project is matched if using the Toggl button from Task details

### Expected behaviour

Project should be automatically chosen if the exact ones exist in Toggl.

### Steps to reproduce

Steps to reproduce the behaviour:

1. Create a project with the same name in Asana and Toggl
2. Go to Asana and click on My Tasks on the left
3. Create TE for that task using TB in Asana
4. It will not pick project.

Screenshot 2020-06-18 at 15 32 15

If you click on a Task and click on TB from there, the Project will match automatically:

Screenshot 2020-06-18 at 16 16 43

### Other details or context

[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/2759100/conversations/24705809818)

### PR DESCRIPTION
**Pull request by lise-toggl**
## :star2: What does this PR do?

- Project names will be picked up again on the My Tasks page
- Move button to far right so they align if a project is present

## :bug: Recommendations for testing

1. Go to My Tasks page
2. Time a task with a project
3. Project is now picked up
4. Icons no longer do this
image

## :memo: Links to relevant issues or information

Closes #1757

### CODE REVIEW

File: src/scripts/content/asana.js [hunk 1]
```diff
@@ -70,18 +70,17 @@ togglbutton.render('.SpreadsheetRow .SpreadsheetTaskName:not(.toggl)', { observe
...
     if (elem.querySelector('.toggl-button')) {
       // Due to the way this UI is rendered, we must check for existence of old buttons manually.
       return;
     }
-    const container = elem.querySelector('.ItemRowTwoColumnStructure-left');
     const descriptionSelector = () => elem.querySelector('.TaskName textarea').textContent;
 
     const projectSelector = () => {
-      const projectElement = elem.querySelector('.TaskRow-pots .Pill');
+      const projectElement = elem.querySelector('.PotPillsContainer');
```
Comment (tcrammond) [inline src/scripts/content/asana.js:83]: This selector doesn't quite work, it will also pick up any tags that are present (breaking the project matching) 😞 since they're all shown as a pill in the same container

Screenshot 2020-06-23 at 11 06 50

actually, I think I've worked on the same bug in the other Asana PR here 🙈  sorry I didn't realise it was an existing issue, just happened to notice it https://github.com/toggl/toggl-button/pull/1762/files#diff-50b20c2c72dfe8169e6d571835144c22R91 

do you want to bring that selector ^ in here (if you test that it works)? since this PR still has some other fixes in it we may as well do it independently of the bigger PR that adds tagging support.

Comment (lise-toggl) [reply src/scripts/content/asana.js:83]: Damn :see_no_evil: 

That selector doesn't match anything for me at all, I wonder if there are multiple Asana views out again? :thinking: 

Here's what it looks like on mine - a red project followed by a red tag - they're identical :sob: 
image

Only thing I can think of is to assume the first pill is a project, and the rest are tags?

Comment (tcrammond) [reply src/scripts/content/asana.js:83]: ^ I think that may be the best course here; will need to test all views with it though

Comment (lise-toggl) [reply src/scripts/content/asana.js]: Updated!

I think the My Tasks page is the only one with this problem, the other views do show tags differently to the project.
