### PR TITLE
Fix asana integration

### LINKED ISSUE #842: Button doesn't show up in personal task list in Asana
In Asana the button only shows up correctly when viewing a task under a project. Opening a task from the "My tasks" list, the button isn't there.

Console shows the following:

screen shot 2017-06-28 at 18 10 45
reported in case 495797

### PR DESCRIPTION
**Pull request by LulzAugusto**
A selector got updated causing the integration to break.

closes #842

### CODE REVIEW

**Comment by LulzAugusto** [comment]
Amended the commit in order to address the issue @syko pointed out.

File: src/scripts/content/asana.js [hunk 1]
```diff
@@ -61,7 +61,7 @@ togglbutton.render('.BoardCard.BoardColumnCardsContainer-item:not(.toggl)', {obs
   var link,
     container = $('.BoardCardMetadata-left', elem),
     description = $('.BoardCard-name', elem).textContent,
-    project = $('#project_pane_header_name').textContent;
+    project = $('.DeprecatedNavigationLink.SidebarItemRow.is-selected').textContent;
```
Comment (Phenome) [inline src/scripts/content/asana.js]: I think we maybe should drop the `DeprecatedNavigationLink` class. `SidebarItemRow` seems enough (tried the querySelector... both returned the same number.
I say this because `DeprecatedNavigationLink` seems like an obvious candidate to be removed soon. Probably will save us some time in the future.

Comment (syko) [inline src/scripts/content/asana.js]: @LulzAugusto I think this is a good point ☝️
