### PR TITLE
Remove "checkPermissions" logic on load/login

### LINKED ISSUE #1663: Opening Chrome causes Toggl button settings to open on every load
* **Windows 10**: 
* **Chrome awaiting more information from user**: 
* Windows v7.4.1112

### 🐛 Describe the bug

The case [here](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097915/conversations/25617417587), is the second case I've seen where a user reports that the Toggl button settings menu opens each time they open Chrome. 

### Expected behaviour

Opening Chrome shouldn't open the Toggl button settings menu

### Steps to reproduce

I cannot reproduce, but the users involved open Chrome, the Toggl button settings open immediately each time.

### PR DESCRIPTION
**Pull request by tcrammond**
Please remember the [Contributing Guidelines](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md) :heart:

## :star2: What does this PR do?

Remove some `checkPermissions` logic that would automatically open the login page if it thinks you don't have any permissions enabled, on load/login (with login meaning, any time user is fetched, I think).

Do not think this is needed any more with the new onboarding page(s).

## :bug: Recommendations for testing

Everything seems sound, and we're not missing out on anything as a result of this change.

## :memo: Links to relevant issues or information

 Closes #1663.

### CODE REVIEW

File: src/scripts/background.js [hunk 1]
```diff
@@ -2254,22 +2253,6 @@ window.TogglButton = {
     }
   },
 
-  checkPermissions: async function (show) {
-    const dontShowPermissions = await db.get('dont-show-permissions');
```
Comment (shantanuraj) [inline src/scripts/background.js]: This PR is good to go!

There's some additional code we can get rid of what do you think?

image

Comment (tcrammond) [reply src/scripts/background.js]: Pushed a commit 🙆‍♂
