### PR TITLE
fix(todoist): Move list item button to far right and only visible on hover

### LINKED ISSUE #1758: Todoist button is not right aligned and is covering long task names
Windows 10
Chrome 83.0.4103.106
1.62.1

### 🐛 Describe the bug

Toggl Button is not right aligned in Todoist and is sitting on top of long task names.

### Expected behaviour

Toggl button would be right aligned and would not sit on top of the task name

### Other details or context

Screenshot from user:
image

[Intercom Link](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/27498501509)

### PR DESCRIPTION
**Pull request by lise-toggl**
## :star2: What does this PR do?

- Fixes button covering up long task names in the inbox when on far left
- Only show on hover in line with other todoist actions
- Removes old todoist list format

## :bug: Recommendations for testing

All changes should be tested across Chrome and Firefox.

1. Create a todoist task with a very long name in the inbox
2. Button no longer covers up part of the task name

## :memo: Links to relevant issues or information

Closes #1758

### CODE REVIEW

File: src/scripts/content/todoist.js [hunk 1]
```diff
@@ -62,14 +27,15 @@ togglbutton.render('[data-item-detail-root] [data-item-actions-root]:not(.toggl)
...
-  elem.insertBefore(wrapper, elem.firstChild);
+  elem.lastChild.before(wrapper);
 });
 
 // task view - subtasks
 togglbutton.render(
   '.task_list_item .task_list_item__actions:not(.toggl)',
   { observe: true, observeTarget: todoistEditor, debounceInterval: 300 },
   elem => {
+    console.log('wotcher', 'elem sub', elem.dataset);
```
Comment (tcrammond) [inline src/scripts/content/todoist.js:38]: wotcher 👋

Comment (lise-toggl) [reply src/scripts/content/todoist.js:38]: wotcher 🖖

:see_no_evil:
