### PR TITLE
fix(trello): Fix Trello integration after UI updates

### LINKED ISSUE #1449: User unable to see Toggl button in his Trello boards
* **OS version**: Windows 10
* **Browser version**: Chrome 75.0.3770.100
* **Extension version**: Version 1.37.4

#### Relevant integration (if any):

Trello (https://trello.com)

### 🐛 Describe the bug

Despite enabling permission for Trello inside the Toggl button settings, user is still unable to see the button. He tried clearing the cache, restarting the browser but the issue persists.

### Expected behaviour

User should see the Toggl button inside the Trello boards but nothing shows up

### Other details or context

I tried to replicate the issue but I can normally see Toggl button in my Trello cards. Other extensions user has are Adobe Acrobat and LINE, disabling them didn't help in resolving the issue.

[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/22720664265)

### LINKED ISSUE #1476: Trello Integration Stopped Working
* **OS version**: 
* **Browser version**: 
* **Extension version**: 

#### Relevant integration (if any):

Trello webapp 

### 🐛 Describe the bug

Timer button does not appear in Trello webapp

### Other details or context

Tested on Chrome with TogglButton 1.40.1

### PR DESCRIPTION
**Pull request by tcrammond**
Please remember the [Contributing Guidelines](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md) :heart:

## :star2: What does this PR do?

* Fixes Trello integration. Some subtle UI updates had broken it.
* Make it not completely error out if the UI has changed again. We'll still of course hear about it not pulling in information if it breaks, but at least it will function.

## :bug: Recommendations for testing

All changes should be tested across Chrome and Firefox.

Please take care that it does work for all cards, and checklist items. Use the `Toggl Button Project` project.

## :memo: Links to relevant issues or information

Closes #1476 and closes #1449

### CODE REVIEW

**Comment by tcrammond** [comment]
👌 pushed a fix @bryanph

File: src/scripts/content/trello.js [hunk 1]
```diff
@@ -47,18 +49,25 @@ togglbutton.render(
   '.checklist-item-details:not(.toggl)',
   { observe: true },
   (elem) => {
-    const titleElem = $('.window-title h2');
-    const taskElem = $('.checklist-item-details-text', elem);
+    const getTitleText = () => {
+      const title = $('.window-title h2', elem);
```
Comment (rylek90) [inline src/scripts/content/trello.js]: `elem` here is checklist item, without `h2` tag inside 🤔 
therefore it always result with empty string
